import type {
  ParsedWorkbook,
  WorkbookCell,
  WorkbookDataRow,
  WorkbookMergeRange,
  WorkbookSheet,
} from "@/utils/workbookParser";

export type SectionOutput = "wide" | "long";

export interface SectionHeaderGroup {
  label: string;
  startColumn: number;
  endColumn: number;
}

export interface SectionHeaderTier {
  rowIndex: number;
  label: string;
  values: WorkbookCell[];
  groups: SectionHeaderGroup[];
}

export interface SectionValueColumn {
  id: string;
  columnIndex: number;
  path: string[];
  label: string;
  leafLabel: string;
  dimensionLabels: string[];
  numericRatio: number;
}

export interface SectionValueGroup {
  id: string;
  label: string;
  columnIds: string[];
}

export interface SectionDataRow {
  id: string;
  rowIndex: number;
  label: string;
  parentId: string | null;
  parentLabel: string | null;
  depth: number;
  descriptorValues: WorkbookCell[];
  isGroup: boolean;
  hasValueData: boolean;
}

export interface SectionRowChoice {
  id: string;
  label: string;
  path: string[];
  rowIndices: number[];
  depth: number;
  kind: "row" | "group" | "child";
}

export interface DetectedTableSection {
  id: string;
  title: string;
  titleRowIndex: number | null;
  headerStartRow: number;
  headerEndRow: number;
  dataStartRow: number;
  dataEndRow: number;
  headerTiers: SectionHeaderTier[];
  rowLabelColumns: number[];
  valueColumns: SectionValueColumn[];
  valueGroups: SectionValueGroup[];
  dataRows: SectionDataRow[];
  rowChoices: SectionRowChoice[];
  mergedSubtitleRows: number[];
  hasMultiTierHeaders: boolean;
  hasMergedSubtitles: boolean;
  hasGroupedCategories: boolean;
  hasExplicitTitle: boolean;
  isStructural: boolean;
  confidence: number;
}

export interface SheetSectionAnalysis {
  sheetId: string;
  sheetName: string;
  width: number;
  sourceRowCount: number;
  headerRowIndex: number;
  sections: DetectedTableSection[];
  recommendedSectionId: string | null;
  hasStructuralContent: boolean;
}

export interface SectionSelection {
  sectionId: string;
  rowChoiceId: string | null;
  valueGroupIds: string[];
  output: SectionOutput;
}

export interface SectionNormalization {
  sheet: WorkbookSheet;
  selection: SectionSelection;
  label: string;
  headers: string[];
  dataMatrix: WorkbookCell[][];
  rowCount: number;
  columnCount: number;
}

interface RowFacts {
  populatedColumns: number[];
  populatedCount: number;
  textCount: number;
  numericCount: number;
  textRatio: number;
  coverage: number;
}

interface ColumnProfile {
  presentCount: number;
  numericCount: number;
  textCount: number;
  numericRatio: number;
  textRatio: number;
}

interface SectionSeed {
  titleRowIndex: number | null;
  headerStartRow: number;
  headerEndRow: number;
  dataEndRow: number;
}

interface MutableDataRow extends SectionDataRow {
  firstDescriptorColumn: number;
  numericOutsideLabels: number;
  childIds: string[];
}

type MergeIndex = Map<number, WorkbookMergeRange[]>;

const MAX_HEADER_TIERS = 6;
const MAX_HEADER_LOOKBACK = 5;
const MAX_TITLE_LOOKBACK = 5;
const MAX_SECTION_SCAN_ROWS = 40;
const MAX_MERGED_RANGES = 50_000;

const EXPLICIT_SECTION_TITLE =
  /^(?:table|exhibit|figure|appendix|annex|panel|part|chapter|section|subsection|schedule)\s*(?:[A-Z]?(?:[\d.]+)|[IVXLC]+)?\b/i;
const DESCRIPTOR_HEADER =
  /^(?:code|codes|id|item|series|metric|measure|variable|field|name|label|description|descriptor|unit|units|region|country|market|sector|industry|sector|subsector|period|year|month|quarter|date|day|week|status|scenario|program|project|headcount|population)$/i;
const PERIOD_LABEL =
  /^(?:(?:19|20)\d{2}(?:[QqEe]\d)?[A-Za-z]?|[QqH](?:[1-4]|\d{2})|[FfYy](?:19|20)?\d{2}|[QqEe][1-4]|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Sept|Oct|Nov|Dec)\s+(?:19|20)\d{2})$/i;
const GROUP_LABEL = /^(?:[MQHAFY]\s*\d+(?:\.\d+)?|[A-Z]?\d+(?:\.\d+)*)$/i;
const FOOTNOTE_LABEL = /^(?:note|notes|source|sources|footnote|legend|prepared by|compiled by|generated by|thank you)\b/i;

/**
 * Converts a cell to a compact display value without losing dates or numeric IDs.
 */
export const cellText = (value: WorkbookCell | undefined): string => {
  if (value === null || value === undefined) return "";
  if (value instanceof Date) {
    return Number.isNaN(value.getTime()) ? "" : value.toISOString().slice(0, 10);
  }
  return String(value).trim();
};

const isBlank = (value: WorkbookCell | undefined): boolean => cellText(value).length === 0;

const isNumeric = (value: WorkbookCell | undefined): boolean => {
  if (typeof value === "number") return Number.isFinite(value);
  if (typeof value !== "string") return false;
  const normalized = value.trim().replace(/[,$%]/g, "").replace(/^\((.*)\)$/, "-$1");
  return normalized.length > 0 && Number.isFinite(Number(normalized));
};

const rowFacts = (row: WorkbookCell[], width: number): RowFacts => {
  const populatedColumns: number[] = [];
  let textCount = 0;
  let numericCount = 0;

  row.forEach((value, columnIndex) => {
    if (isBlank(value)) return;
    populatedColumns.push(columnIndex);
    if (isNumeric(value)) numericCount += 1;
    else textCount += 1;
  });

  const populatedCount = populatedColumns.length;
  return {
    populatedColumns,
    populatedCount,
    textCount,
    numericCount,
    textRatio: populatedCount > 0 ? textCount / populatedCount : 0,
    coverage: width > 0 ? populatedCount / width : 0,
  };
};

const rectangularMatrix = (rows: WorkbookCell[][]): WorkbookCell[][] => {
  const width = rows.reduce((maximum, row) => Math.max(maximum, row.length), 0);
  return rows.map((row) => Array.from({ length: width }, (_, index) => row[index] ?? null));
};

const sourceMatrixFor = (sheet: WorkbookSheet): WorkbookCell[][] => {
  if (sheet.sourceMatrix.length > 0) return rectangularMatrix(sheet.sourceMatrix);
  if (sheet.headers.length === 0 && sheet.dataMatrix.length === 0) return [];
  return rectangularMatrix([[...sheet.headers], ...sheet.dataMatrix]);
};

const makeMergeIndex = (ranges: WorkbookMergeRange[]): MergeIndex => {
  const index: MergeIndex = new Map();
  ranges.slice(0, MAX_MERGED_RANGES).forEach((range) => {
    for (let rowIndex = range.startRow; rowIndex <= range.endRow; rowIndex += 1) {
      const rowRanges = index.get(rowIndex) ?? [];
      rowRanges.push(range);
      index.set(rowIndex, rowRanges);
    }
  });
  return index;
};

const mergeAt = (
  index: MergeIndex,
  rowIndex: number,
  columnIndex: number
): WorkbookMergeRange | null => {
  const ranges = index.get(rowIndex);
  if (!ranges) return null;
  return (
    ranges.find(
      (range) => columnIndex >= range.startColumn && columnIndex <= range.endColumn
    ) ?? null
  );
};

const valueAt = (
  matrix: WorkbookCell[][],
  merges: MergeIndex,
  rowIndex: number,
  columnIndex: number
): WorkbookCell => {
  const direct = matrix[rowIndex]?.[columnIndex] ?? null;
  if (!isBlank(direct)) return direct;
  const merge = mergeAt(merges, rowIndex, columnIndex);
  return merge ? matrix[merge.startRow]?.[merge.startColumn] ?? null : null;
};

const hasHorizontalMergeAt = (merges: MergeIndex, rowIndex: number): boolean =>
  (merges.get(rowIndex) ?? []).some((range) => range.endColumn > range.startColumn);

const isExplicitTitle = (value: string): boolean => {
  const label = value.trim();
  if (!label) return false;
  return (
    EXPLICIT_SECTION_TITLE.test(label) ||
    /^(?:TABLE|EXHIBIT|FIGURE|APPENDIX|ANNEX|SECTION)\s+[A-Z]?[\d.]+[A-Z]?$/i.test(label)
  );
};

const compactLabel = (value: string): string => value.trim().replace(/\s+/g, " ");

const titleText = (row: WorkbookCell[]): string =>
  row
    .map(cellText)
    .filter(Boolean)
    .map(compactLabel)
    .filter((label, index, labels) => label !== labels[index - 1])
    .join(" · ");

const slug = (value: string): string =>
  value
    .toLocaleLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "value";

const nextPopulatedRow = (matrix: WorkbookCell[][], start: number): number => {
  for (let rowIndex = start; rowIndex < matrix.length; rowIndex += 1) {
    if (rowFacts(matrix[rowIndex] ?? [], matrix[rowIndex]?.length ?? 0).populatedCount > 0) {
      return rowIndex;
    }
  }
  return -1;
};

const hasRepeatedLabels = (labels: string[]): boolean => {
  for (let index = 1; index < labels.length; index += 1) {
    if (labels[index] === labels[index - 1] && labels[index]) return true;
  }
  const groupCount = labels.filter((label) => GROUP_LABEL.test(label)).length;
  return groupCount >= Math.max(2, Math.ceil(labels.length * 0.5));
};

const isTitleCandidate = (
  matrix: WorkbookCell[][],
  rowIndex: number,
  width: number,
  merges: MergeIndex
): boolean => {
  const row = matrix[rowIndex] ?? [];
  const facts = rowFacts(row, width);
  if (facts.populatedCount === 0 || facts.numericCount > 0) return false;

  const labels = facts.populatedColumns
    .map((columnIndex) => cellText(row[columnIndex]))
    .filter(Boolean);
  if (labels.some(isExplicitTitle)) return true;

  const sparseLimit = Math.max(2, Math.ceil(width * 0.3));
  if (facts.populatedCount > sparseLimit || labels.some((label) => label.length > 180)) {
    return false;
  }

  return (
    hasHorizontalMergeAt(merges, rowIndex) ||
    (facts.populatedCount === 1 && hasUpcomingHeader(matrix, rowIndex, width, merges))
  );
};

/**
 * Scores a row as a header without treating a title or a compact parent row as
 * a header. Periods such as 2024 and M3 are intentionally recognized as labels.
 */
const headerQuality = (row: WorkbookCell[], width: number, merged: boolean): number => {
  const facts = rowFacts(row, width);
  if (facts.populatedCount === 0) return 0;
  if (facts.populatedColumns.some((columnIndex) => isExplicitTitle(cellText(row[columnIndex])))) {
    return 0.08;
  }
  if (facts.populatedCount > Math.max(2, width) || row.some((value) => cellText(value).length > 160)) {
    return 0;
  }

  const minimum = width <= 2 ? 1 : 2;
  if (facts.populatedCount < minimum || facts.coverage < 0.16) return 0;

  const labels = facts.populatedColumns.map((columnIndex) => cellText(row[columnIndex]));
  if (facts.textCount === 0 && !labels.every((label) => PERIOD_LABEL.test(label))) return 0;
  const descriptorCount = labels.filter((label) => DESCRIPTOR_HEADER.test(label)).length;
  const periodCount = labels.filter((label) => PERIOD_LABEL.test(label)).length;
  const groupCount = labels.filter((label) => GROUP_LABEL.test(label)).length;
  const repeated = hasRepeatedLabels(labels);
  const unknownNumericRatio =
    facts.populatedCount > 0 ? (facts.numericCount - periodCount) / facts.populatedCount : 0;

  return Math.max(
    0,
    Math.min(
      1,
      0.12 +
        facts.coverage * 0.23 +
        facts.textRatio * 0.18 +
        Math.min(1, descriptorCount / Math.max(1, Math.min(facts.populatedCount, 2))) * 0.3 +
        Math.min(1, periodCount / facts.populatedCount) * 0.24 +
        Math.min(1, groupCount / Math.max(1, facts.populatedCount)) * 0.18 +
        (repeated ? 0.12 : 0) +
        (merged ? 0.12 : 0) -
        Math.max(0, unknownNumericRatio) * 0.5
    )
  );
};

const hasDataAfter = (matrix: WorkbookCell[][], rowIndex: number, width: number): boolean => {
  for (let index = rowIndex + 1; index < Math.min(matrix.length, rowIndex + 7); index += 1) {
    const facts = rowFacts(matrix[index] ?? [], width);
    if (facts.populatedCount < (width <= 2 ? 1 : 2)) continue;
    if (facts.numericCount > 0 || facts.textCount > 0) return true;
  }
  return false;
};

const hasUpcomingHeader = (
  matrix: WorkbookCell[][],
  rowIndex: number,
  width: number,
  merges: MergeIndex
): boolean => {
  for (
    let index = rowIndex + 1;
    index < Math.min(matrix.length, rowIndex + MAX_HEADER_TIERS + 1);
    index += 1
  ) {
    const row = matrix[index] ?? [];
    if (rowFacts(row, width).populatedCount === 0) continue;
    if (headerQuality(row, width, hasHorizontalMergeAt(merges, index)) >= 0.58) return true;
  }
  return false;
};

const isHeaderLike = (
  matrix: WorkbookCell[][],
  rowIndex: number,
  width: number,
  merges: MergeIndex
): boolean => {
  const row = matrix[rowIndex] ?? [];
  return headerQuality(row, width, hasHorizontalMergeAt(merges, rowIndex)) >= 0.53;
};

const hasHeaderEvidence = (
  matrix: WorkbookCell[][],
  rowIndex: number,
  width: number,
  merges: MergeIndex
): boolean =>
  isHeaderLike(matrix, rowIndex, width, merges) &&
  (hasDataAfter(matrix, rowIndex, width) || hasUpcomingHeader(matrix, rowIndex, width, merges));

const findInitialHeaderRow = (
  matrix: WorkbookCell[][],
  width: number,
  merges: MergeIndex
): number => {
  const candidates: { rowIndex: number; score: number }[] = [];
  const limit = Math.min(matrix.length, MAX_SECTION_SCAN_ROWS);

  for (let rowIndex = 0; rowIndex < limit; rowIndex += 1) {
    if (!hasHeaderEvidence(matrix, rowIndex, width, merges)) continue;
    const row = matrix[rowIndex] ?? [];
    const facts = rowFacts(row, width);
    const labels = facts.populatedColumns.map((columnIndex) => cellText(row[columnIndex]));
    const descriptorCount = labels.filter((label) => DESCRIPTOR_HEADER.test(label)).length;
    const merged = hasHorizontalMergeAt(merges, rowIndex) ? 0.4 : 0;
    const score = headerQuality(row, width, merged > 0) * 2 + facts.coverage + descriptorCount + merged;
    candidates.push({ rowIndex, score });
  }

  if (candidates.length > 0) {
    const firstCandidate = candidates[0];
    const initialBlock = candidates.filter(
      (candidate) => candidate.rowIndex <= firstCandidate.rowIndex + MAX_HEADER_TIERS
    );
    return initialBlock.reduce((best, candidate) =>
      candidate.score > best.score ? candidate : best
    ).rowIndex;
  }

  return nextPopulatedRow(matrix, 0);
};

/**
 * Walks backwards from the leaf header to include merged groups (M3, M2),
 * period bands, and explicit descriptor rows, without swallowing the last
 * category row belonging to the previous table.
 */
const expandHeaderStart = (
  matrix: WorkbookCell[][],
  headerEndRow: number,
  width: number,
  merges: MergeIndex
): number => {
  let start = headerEndRow;
  const minimum = Math.max(0, headerEndRow - MAX_HEADER_LOOKBACK);

  for (let rowIndex = headerEndRow - 1; rowIndex >= minimum; rowIndex -= 1) {
    const row = matrix[rowIndex] ?? [];
    const facts = rowFacts(row, width);
    if (facts.populatedCount === 0) break;
    if (!isHeaderLike(matrix, rowIndex, width, merges)) break;

    const labels = facts.populatedColumns.map((columnIndex) => cellText(row[columnIndex]));
    const isStructuralRow =
      hasHorizontalMergeAt(merges, rowIndex) ||
      hasRepeatedLabels(labels) ||
      labels.some((label) => PERIOD_LABEL.test(label) || GROUP_LABEL.test(label)) ||
      labels.some((label) => DESCRIPTOR_HEADER.test(label));
    if (!isStructuralRow) break;
    start = rowIndex;
  }

  return start;
};

const findTitleRow = (
  matrix: WorkbookCell[][],
  headerStartRow: number,
  width: number,
  merges: MergeIndex
): number | null => {
  const minimum = Math.max(0, headerStartRow - MAX_TITLE_LOOKBACK);
  for (let rowIndex = headerStartRow - 1; rowIndex >= minimum; rowIndex -= 1) {
    const facts = rowFacts(matrix[rowIndex] ?? [], width);
    if (facts.populatedCount === 0) continue;
    return isTitleCandidate(matrix, rowIndex, width, merges) ? rowIndex : null;
  }
  return null;
};

const signatureSimilarity = (row: WorkbookCell[], reference: ReadonlySet<number>): number => {
  const columns = new Set(rowStatsColumns(row));
  if (columns.size === 0 || reference.size === 0) return 0;
  let overlap = 0;
  columns.forEach((column) => {
    if (reference.has(column)) overlap += 1;
  });
  return overlap / Math.max(columns.size, reference.size);
};

const rowStatsColumns = (row: WorkbookCell[]): number[] =>
  row.reduce<number[]>((columns, value, columnIndex) => {
    if (!isBlank(value)) columns.push(columnIndex);
    return columns;
  }, []);

const hasMeaningfulDataRun = (
  matrix: WorkbookCell[][],
  startRow: number,
  endRow: number,
  width: number,
  merges: MergeIndex
): boolean => {
  for (let rowIndex = startRow; rowIndex < endRow; rowIndex += 1) {
    const facts = rowStatsForWidth(matrix[rowIndex] ?? [], width);
    if (facts.populatedCount < (width <= 2 ? 1 : 2)) continue;
    if (!isHeaderLike(matrix, rowIndex, width, merges)) return true;
  }
  return false;
};

const rowStatsForWidth = (row: WorkbookCell[], width: number): RowFacts => rowFacts(row, width);

const bestHeaderAnchor = (
  matrix: WorkbookCell[][],
  startRow: number,
  endRow: number,
  width: number,
  merges: MergeIndex
): number => {
  const candidates: { rowIndex: number; score: number }[] = [];
  const minimum = Math.max(0, startRow);
  const maximum = Math.min(matrix.length - 1, endRow);

  for (let rowIndex = minimum; rowIndex <= maximum; rowIndex += 1) {
    if (!hasHeaderEvidence(matrix, rowIndex, width, merges)) continue;
    const row = matrix[rowIndex] ?? [];
    const facts = rowStatsForWidth(row, width);
    const labels = facts.populatedColumns.map((columnIndex) => cellText(row[columnIndex]));
    const descriptorCount = labels.filter((label) => DESCRIPTOR_HEADER.test(label)).length;
    candidates.push({
      rowIndex,
      score: headerQuality(row, width, hasHorizontalMergeAt(merges, rowIndex)) * 2 +
        descriptorCount +
        (hasHorizontalMergeAt(merges, rowIndex) ? 0.25 : 0),
    });
  }

  if (candidates.length === 0) return -1;
  return candidates.reduce((best, candidate) => (candidate.score > best.score ? candidate : best))
    .rowIndex;
};

/**
 * Finds table seeds at titles, repeated header signatures, and deliberate
 * blank-row boundaries. A blank row alone is never considered a table.
 */
const detectSectionSeeds = (
  matrix: WorkbookCell[][],
  width: number,
  initialHeaderRow: number,
  merges: MergeIndex
): SectionSeed[] => {
  if (initialHeaderRow < 0 || initialHeaderRow >= matrix.length) return [];

  const initialStart = expandHeaderStart(matrix, initialHeaderRow, width, merges);
  const seeds: SectionSeed[] = [
    {
      titleRowIndex: findTitleRow(matrix, initialStart, width, merges),
      headerStartRow: initialStart,
      headerEndRow: initialHeaderRow,
      dataEndRow: Math.max(initialHeaderRow, matrix.length - 1),
    },
  ];
  const referenceColumns = new Set(rowStatsColumns(matrix[initialHeaderRow] ?? []));
  let scanFrom = initialHeaderRow + 1;

  for (let rowIndex = scanFrom; rowIndex < matrix.length; ) {
    const facts = rowStatsForWidth(matrix[rowIndex] ?? [], width);
    if (facts.populatedCount === 0) {
      rowIndex += 1;
      continue;
    }

    const previousPopulated = previousNonBlankRow(matrix, rowIndex);
    const hasBlankBoundary =
      previousPopulated < 0 || rowIndex - previousPopulated > 1;
    const hasTitle = isTitleCandidate(matrix, rowIndex, width, merges);
    const repeatedHeader =
      isHeaderLike(matrix, rowIndex, width, merges) &&
      signatureSimilarity(matrix[rowIndex] ?? [], referenceColumns) >= 0.5;
    const dataSinceLastSeed = hasMeaningfulDataRun(
      matrix,
      seeds[seeds.length - 1].headerEndRow + 1,
      rowIndex,
      width,
      merges
    );

    if (!(hasBlankBoundary || hasTitle || (repeatedHeader && dataSinceLastSeed))) {
      rowIndex += 1;
      continue;
    }

    const searchStart = hasTitle ? rowIndex + 1 : rowIndex;
    const searchEnd = Math.min(matrix.length - 1, searchStart + MAX_HEADER_TIERS - 1);
    const anchor = bestHeaderAnchor(matrix, searchStart, searchEnd, width, merges);
    if (anchor < 0) {
      rowIndex += 1;
      continue;
    }

    const start = expandHeaderStart(matrix, anchor, width, merges);
    if (seeds.some((seed) => seed.headerEndRow >= anchor || seed.headerStartRow === start)) {
      rowIndex = anchor + 1;
      continue;
    }

    seeds.push({
      titleRowIndex: hasTitle ? rowIndex : findTitleRow(matrix, start, width, merges),
      headerStartRow: start,
      headerEndRow: anchor,
      dataEndRow: Math.max(anchor, matrix.length - 1),
    });
    rowIndex = anchor + 1;
  }

  return seeds
    .sort((left, right) => left.headerStartRow - right.headerStartRow)
    .map((seed, index, ordered) => {
      const next = ordered[index + 1];
      const boundary = next ? next.titleRowIndex ?? next.headerStartRow : matrix.length;
      return { ...seed, dataEndRow: Math.max(seed.headerEndRow, boundary - 1) };
    });
};

const previousNonBlankRow = (matrix: WorkbookCell[][], beforeRow: number): number => {
  for (let rowIndex = beforeRow - 1; rowIndex >= 0; rowIndex -= 1) {
    if (rowFacts(matrix[rowIndex] ?? [], matrix[rowIndex]?.length ?? 0).populatedCount > 0) {
      return rowIndex;
    }
  }
  return -1;
};

const headerGroups = (values: WorkbookCell[]): SectionHeaderGroup[] => {
  const groups: SectionHeaderGroup[] = [];
  values.forEach((value, columnIndex) => {
    const label = cellText(value);
    if (!label) return;
    const previous = groups[groups.length - 1];
    if (previous?.label === label && previous.endColumn === columnIndex - 1) {
      previous.endColumn = columnIndex;
    } else {
      groups.push({ label, startColumn: columnIndex, endColumn: columnIndex });
    }
  });
  return groups;
};

const buildHeaderTiers = (
  matrix: WorkbookCell[][],
  startRow: number,
  endRow: number,
  merges: MergeIndex
): SectionHeaderTier[] => {
  const tiers: SectionHeaderTier[] = [];
  for (let rowIndex = startRow; rowIndex <= endRow; rowIndex += 1) {
    const values = (matrix[rowIndex] ?? []).map((_, columnIndex) =>
      valueAt(matrix, merges, rowIndex, columnIndex)
    );
    const labels = values
      .map(cellText)
      .filter(Boolean)
      .filter((label, index, all) => label !== all[index - 1]);
    tiers.push({
      rowIndex,
      label: Array.from(new Set(labels)).join(" / "),
      values,
      groups: headerGroups(values),
    });
  }
  return tiers;
};

const columnProfiles = (
  matrix: WorkbookCell[][],
  rowIndices: number[],
  width: number
): ColumnProfile[] =>
  Array.from({ length: width }, (_, columnIndex) => {
    let presentCount = 0;
    let numericCount = 0;
    let textCount = 0;
    rowIndices.forEach((rowIndex) => {
      const value = matrix[rowIndex]?.[columnIndex] ?? null;
      if (isBlank(value)) return;
      presentCount += 1;
      if (isNumeric(value)) numericCount += 1;
      else textCount += 1;
    });
    return {
      presentCount,
      numericCount,
      textCount,
      numericRatio: presentCount > 0 ? numericCount / presentCount : 0,
      textRatio: presentCount > 0 ? textCount / presentCount : 0,
    };
  });

const headerPath = (tiers: SectionHeaderTier[], columnIndex: number): string[] => {
  const labels = tiers
    .map((tier) => cellText(tier.values[columnIndex]))
    .filter(Boolean)
    .filter((label, index, all) => label !== all[index - 1]);
  return labels.length > 0 ? labels : [`Column ${columnIndex + 1}`];
};

const isLikelyMeasureLabel = (label: string): boolean =>
  PERIOD_LABEL.test(label) ||
  /^(?:value|values|amount|number|count|rate|ratio|share|percent|percentage|usd|gbp|eur|ngn|\$|£|€|%|m3|m2|actual|forecast|estimate|projected|target|budget|real|nominal)$/i.test(
    label
  );

const isIdentifierHeader = (path: string[]): boolean => {
  const leaf = path[path.length - 1] ?? "";
  return DESCRIPTOR_HEADER.test(leaf) || /^(?:row|item|series|description|entity)/i.test(leaf);
};

const descriptorColumns = (
  profiles: ColumnProfile[],
  headerPaths: string[][],
  width: number,
  dataRowCount: number
): number[] => {
  const firstNumeric = profiles.findIndex(
    (profile) => profile.numericRatio >= 0.28 && profile.presentCount >= Math.max(1, dataRowCount * 0.12)
  );
  const firstMeasureHeader = headerPaths.findIndex((path, columnIndex) => {
    const leaf = path[path.length - 1] ?? "";
    return (
      isLikelyMeasureLabel(leaf) &&
      (profiles[columnIndex].numericRatio >= 0.28 ||
        /^(?:value|values|amount|number|count|rate|ratio|share|percent|percentage|usd|gbp|eur|ngn|actual|forecast|estimate|projected|target|budget|real|nominal)$/i.test(leaf))
    );
  });
  const firstValue = [firstNumeric, firstMeasureHeader]
    .filter((index) => index >= 0)
    .sort((left, right) => left - right)[0];
  const leadingLimit = firstValue >= 0 ? firstValue : Math.min(width, width > 3 ? 2 : width);
  const selected = new Set<number>();

  for (let columnIndex = 0; columnIndex < leadingLimit; columnIndex += 1) {
    if (profiles[columnIndex].presentCount > 0 || headerPaths[columnIndex]?.length) {
      selected.add(columnIndex);
    }
  }
  headerPaths.forEach((path, columnIndex) => {
    if (isIdentifierHeader(path) && columnIndex < leadingLimit) selected.add(columnIndex);
  });

  if (selected.size === 0) {
    const firstPresent = profiles.findIndex((profile) => profile.presentCount > 0);
    if (firstPresent >= 0) selected.add(firstPresent);
  }
  return Array.from(selected).sort((left, right) => left - right);
};

const dataLabel = (row: WorkbookCell[], columns: number[]): string => {
  const labels = columns
    .map((columnIndex) => cellText(row[columnIndex]))
    .filter(Boolean)
    .filter((label, index, all) => label !== all[index - 1]);
  return labels.join(" · ") || row.map(cellText).find(Boolean) || "";
};

const isFootnote = (row: WorkbookCell[], labelColumns: number[]): boolean => {
  const facts = rowStatsForWidth(row, row.length);
  if (facts.numericCount > 0) return false;
  const labels = labelColumns
    .map((columnIndex) => cellText(row[columnIndex]))
    .filter(Boolean);
  return labels.some((label) => FOOTNOTE_LABEL.test(label)) && facts.textCount <= 3;
};

const buildRowsAndChoices = (
  sectionId: string,
  matrix: WorkbookCell[][],
  dataRowIndices: number[],
  rowLabelColumns: number[]
): { dataRows: SectionDataRow[]; rowChoices: SectionRowChoice[] } => {
  const labelColumnSet = new Set(rowLabelColumns);
  const mutableRows: MutableDataRow[] = dataRowIndices.map((rowIndex) => {
    const row = matrix[rowIndex] ?? [];
    const descriptorValues = rowLabelColumns.map((columnIndex) => row[columnIndex] ?? null);
    const numericOutsideLabels = row.reduce<number>(
      (count, value, columnIndex) =>
        count + (!labelColumnSet.has(columnIndex) && isNumeric(value) ? 1 : 0),
      0
    );
    const textOutsideLabels = row.reduce<number>(
      (count, value, columnIndex) =>
        count + (!labelColumnSet.has(columnIndex) && !isBlank(value) ? 1 : 0),
      0
    );
    const firstDescriptorColumn = row.findIndex(
      (value, columnIndex) => labelColumnSet.has(columnIndex) && !isBlank(value)
    );
    const label = dataLabel(row, rowLabelColumns) || `Row ${rowIndex + 1}`;
    return {
      id: `${sectionId}:row:${rowIndex}`,
      rowIndex,
      label,
      parentId: null,
      parentLabel: null,
      depth: 0,
      descriptorValues,
      isGroup: false,
      hasValueData: numericOutsideLabels > 0 || textOutsideLabels > 0,
      numericOutsideLabels,
      firstDescriptorColumn: firstDescriptorColumn < 0 ? row.length : firstDescriptorColumn,
      childIds: [],
    };
  });

  // A label-only row is a possible parent. The nearest less-indented label row
  // becomes its parent; a later value-bearing row inherits the same chain.
  for (let index = 0; index < mutableRows.length; index += 1) {
    const current = mutableRows[index];
    for (let previousIndex = index - 1; previousIndex >= 0; previousIndex -= 1) {
      const previous = mutableRows[previousIndex];
      if (previous.firstDescriptorColumn < current.firstDescriptorColumn) {
        if (!previous.hasValueData && current.firstDescriptorColumn > 0) {
          current.parentId = previous.id;
        }
        break;
      }
      if (previous.firstDescriptorColumn > current.firstDescriptorColumn) {
        // We have reached a more deeply indented parent than the current row.
        if (previous.parentId) continue;
        break;
      }
    }

    if (current.hasValueData || current.firstDescriptorColumn <= 0) continue;
    const parent = mutableRows
      .slice(0, index)
      .reverse()
      .find((candidate) => candidate.firstDescriptorColumn < current.firstDescriptorColumn);
    if (parent && !parent.hasValueData) current.parentId = parent.id;
  }

  const rowById = new Map(mutableRows.map((row) => [row.id, row]));
  mutableRows.forEach((row) => {
    if (!row.parentId) return;
    const parent = rowById.get(row.parentId);
    if (!parent) return;
    row.parentLabel = parent.label;
    parent.childIds.push(row.id);
  });

  const depthFor = (row: MutableDataRow): number => {
    const visited = new Set<string>();
    let depth = 0;
    let current: MutableDataRow | undefined = row;
    while (current?.parentId && !visited.has(current.id)) {
      visited.add(current.id);
      depth += 1;
      current = rowById.get(current.parentId);
    }
    return depth;
  };
  mutableRows.forEach((row) => {
    row.depth = depthFor(row);
    row.isGroup = !row.hasValueData && row.childIds.length > 0;
  });

  const rowChoices: SectionRowChoice[] = [];
  const pathFor = (row: MutableDataRow): string[] => {
    const labels: string[] = [];
    let current: MutableDataRow | undefined = row;
    const visited = new Set<string>();
    while (current && !visited.has(current.id)) {
      visited.add(current.id);
      labels.unshift(current.label);
      current = current.parentId ? rowById.get(current.parentId) : undefined;
    }
    return labels.filter((label, index, all) => label && label !== all[index - 1]);
  };
  const descendantsOf = (row: MutableDataRow): MutableDataRow[] => {
    const descendants: MutableDataRow[] = [];
    const pending = [...row.childIds];
    while (pending.length > 0) {
      const child = rowById.get(pending.shift() ?? "");
      if (!child) continue;
      if (child.hasValueData) descendants.push(child);
      pending.push(...child.childIds);
    }
    return descendants;
  };

  mutableRows.forEach((row) => {
    if (row.parentId && !row.isGroup) return;
    const path = pathFor(row);
    if (row.isGroup) {
      const children = descendantsOf(row);
      if (children.length === 0) return;
      rowChoices.push({
        id: `${row.id}:group`,
        label: row.label,
        path,
        rowIndices: children.map((child) => child.rowIndex).sort((left, right) => left - right),
        depth: row.depth,
        kind: "group",
      });
      children.forEach((child) => {
        rowChoices.push({
          id: `${child.id}:choice`,
          label: child.label,
          path: pathFor(child),
          rowIndices: [child.rowIndex],
          depth: child.depth,
          kind: "child",
        });
      });
      return;
    }
    if (!row.hasValueData) return;
    rowChoices.push({
      id: `${row.id}:choice`,
      label: row.label,
      path,
      rowIndices: [row.rowIndex],
      depth: row.depth,
      kind: row.parentId ? "child" : "row",
    });
  });

  return {
    dataRows: mutableRows.map(
      ({ numericOutsideLabels, firstDescriptorColumn, childIds, ...row }) => {
        void numericOutsideLabels;
        void firstDescriptorColumn;
        void childIds;
        return row;
      }
    ),
    rowChoices,
  };
};

const mergedRowsInSection = (
  sheet: WorkbookSheet,
  seed: SectionSeed
): number[] => {
  const rows = new Set<number>();
  sheet.mergedRanges
    .filter(
      (range) =>
        range.endColumn > range.startColumn &&
        range.startRow <= seed.headerEndRow &&
        range.endRow >= (seed.titleRowIndex ?? seed.headerStartRow)
    )
    .forEach((range) => {
      for (let rowIndex = range.startRow; rowIndex <= range.endRow; rowIndex += 1) {
        rows.add(rowIndex);
      }
    });
  return Array.from(rows).sort((left, right) => left - right);
};

const buildSection = (
  sheet: WorkbookSheet,
  matrix: WorkbookCell[][],
  width: number,
  seed: SectionSeed,
  sectionIndex: number,
  merges: MergeIndex
): DetectedTableSection => {
  const sectionId = `${sheet.id}:section:${seed.headerStartRow}:${seed.headerEndRow}`;
  const headerTiers = buildHeaderTiers(matrix, seed.headerStartRow, seed.headerEndRow, merges);
  const dataEndRow = seed.dataEndRow;
  const allDataRowIndices = Array.from(
    { length: Math.max(0, dataEndRow - seed.headerEndRow) },
    (_, offset) => seed.headerEndRow + 1 + offset
  );
  const headerPaths = Array.from({ length: width }, (_, columnIndex) =>
    headerPath(headerTiers, columnIndex)
  );
  const profiles = columnProfiles(matrix, allDataRowIndices, width);
  const rowLabels = descriptorColumns(profiles, headerPaths, width, allDataRowIndices.length);
  const labelSet = new Set(rowLabels);
  const valueColumnIndices = Array.from({ length: width }, (_, columnIndex) => columnIndex).filter(
    (columnIndex) =>
      !labelSet.has(columnIndex) &&
      (profiles[columnIndex].presentCount > 0 || isLikelyMeasureLabel(headerPaths[columnIndex]?.[headerPaths[columnIndex].length - 1] ?? ""))
  );
  const valueColumns: SectionValueColumn[] = valueColumnIndices.map((columnIndex) => {
    const path = headerPaths[columnIndex];
    const leafLabel = path[path.length - 1] ?? `Column ${columnIndex + 1}`;
    return {
      id: `${sectionId}:column:${columnIndex}`,
      columnIndex,
      path,
      label: path.join(" · "),
      leafLabel,
      dimensionLabels: path.slice(0, -1),
      numericRatio: profiles[columnIndex].numericRatio,
    };
  });

  // Group by the complete dimension path. This keeps M3 and M2 as separate
  // lanes while retaining repeated year/quarter labels under their lane.
  const groups = new Map<string, SectionValueGroup>();
  valueColumns.forEach((column) => {
    const dimensionLabels = column.dimensionLabels.filter(Boolean);
    const groupKey = dimensionLabels.length > 0 ? dimensionLabels.join(" · ") : column.leafLabel;
    const group = groups.get(groupKey) ?? {
      id: `${sectionId}:group:${slug(groupKey)}`,
      label: groupKey,
      columnIds: [],
    };
    group.columnIds.push(column.id);
    groups.set(groupKey, group);
  });
  const valueGroups = Array.from(groups.values());

  const provisionalRows = allDataRowIndices.filter((rowIndex) => {
    const row = matrix[rowIndex] ?? [];
    return rowStatsForWidth(row, width).populatedCount > 0 && !isFootnote(row, rowLabels);
  });
  const { dataRows, rowChoices } = buildRowsAndChoices(
    sectionId,
    matrix,
    provisionalRows,
    rowLabels
  );
  const title =
    seed.titleRowIndex === null
      ? `Table ${sectionIndex + 1}`
      : titleText(matrix[seed.titleRowIndex] ?? []) || `Table ${sectionIndex + 1}`;
  const mergedSubtitleRows = mergedRowsInSection(sheet, seed);
  const hasChildRows = dataRows.some((row) => row.isGroup);
  const hasMultiTierHeaders = headerTiers.length > 1;
  const hasMergedSubtitles = mergedSubtitleRows.length > 0;
  const distinctColumnLanes = new Set(
    valueColumns
      .map((column) => column.dimensionLabels.join(" · "))
      .filter(Boolean)
  );
  const hasGroupedCategories =
    hasChildRows ||
    valueGroups.some((group) => group.columnIds.length > 1) ||
    (hasMultiTierHeaders && distinctColumnLanes.size > 1);
  const hasExplicitTitle = seed.titleRowIndex !== null;
  const isStructural =
    hasMultiTierHeaders || hasMergedSubtitles || hasGroupedCategories || hasExplicitTitle;
  const confidence = Math.min(
    0.99,
    0.55 +
      (hasExplicitTitle ? 0.1 : 0) +
      (hasMultiTierHeaders ? 0.15 : 0) +
      (hasMergedSubtitles ? 0.08 : 0) +
      (hasGroupedCategories ? 0.08 : 0) +
      (hasChildRows ? 0.04 : 0)
  );
  const lastDataRow = provisionalRows.at(-1) ?? seed.headerEndRow;

  return {
    id: sectionId,
    title,
    titleRowIndex: seed.titleRowIndex,
    headerStartRow: seed.headerStartRow,
    headerEndRow: seed.headerEndRow,
    dataStartRow: seed.headerEndRow + 1,
    dataEndRow: lastDataRow,
    headerTiers,
    rowLabelColumns: rowLabels,
    valueColumns,
    valueGroups,
    dataRows,
    rowChoices,
    mergedSubtitleRows,
    hasMultiTierHeaders,
    hasMergedSubtitles,
    hasGroupedCategories,
    hasExplicitTitle,
    isStructural,
    confidence,
  };
};

export const analyzeSheetSections = (sheet: WorkbookSheet): SheetSectionAnalysis => {
  const matrix = sourceMatrixFor(sheet);
  const width = matrix.reduce((maximum, row) => Math.max(maximum, row.length), 0);
  const merges = makeMergeIndex(sheet.mergedRanges);
  const initialHeaderRow =
    sheet.headerRowIndex >= 0 && sheet.headerRowIndex < matrix.length
      ? sheet.headerRowIndex
      : findInitialHeaderRow(matrix, width, merges);
  const seeds = detectSectionSeeds(matrix, width, initialHeaderRow, merges);
  const sections = seeds
    .map((seed, index) => buildSection(sheet, matrix, width, seed, index, merges))
    .filter((section) => section.dataRows.length > 0 || section.headerTiers.length > 0);
  const recommended = sections.reduce<DetectedTableSection | null>((best, section) => {
    if (!best) return section;
    const bestScore = best.dataRows.filter((row) => row.hasValueData).length;
    const sectionScore = section.dataRows.filter((row) => row.hasValueData).length;
    if (sectionScore > bestScore) return section;
    if (sectionScore === bestScore && section.confidence > best.confidence) return section;
    return best;
  }, null);

  return {
    sheetId: sheet.id,
    sheetName: sheet.name,
    width,
    sourceRowCount: matrix.length,
    headerRowIndex: initialHeaderRow,
    sections,
    recommendedSectionId: recommended?.id ?? null,
    hasStructuralContent: sections.some((section) => section.isStructural),
  };
};

export const analyzeWorkbookSections = (workbook: ParsedWorkbook): SheetSectionAnalysis[] =>
  workbook.sheets.map(analyzeSheetSections);

export const createDefaultSectionSelection = (
  analysis: SheetSectionAnalysis,
  sectionId = analysis.recommendedSectionId
): SectionSelection => {
  const section = analysis.sections.find((candidate) => candidate.id === sectionId);
  return {
    sectionId: section?.id ?? analysis.sections[0]?.id ?? "",
    rowChoiceId: null,
    valueGroupIds: section?.valueGroups.map((group) => group.id) ?? [],
    output: "wide",
  };
};

const defineRowValue = (row: WorkbookDataRow, key: string, value: WorkbookCell): void => {
  Object.defineProperty(row, key, {
    configurable: true,
    enumerable: true,
    value,
    writable: true,
  });
};

const rowsFromMatrix = (matrix: WorkbookCell[][], headers: string[]): WorkbookDataRow[] =>
  matrix.map((values) => {
    const row: WorkbookDataRow = {};
    headers.forEach((header, index) => defineRowValue(row, header, values[index] ?? null));
    return row;
  });

const uniqueHeaders = (values: string[]): string[] => {
  const counts = new Map<string, number>();
  return values.map((value) => {
    const base = value.trim() || "Column";
    const count = counts.get(base) ?? 0;
    counts.set(base, count + 1);
    return count === 0 ? base : `${base} (${count + 1})`;
  });
};

const dimensionHeader = (labels: string[], index: number, used: Set<string>): string => {
  const unique = Array.from(new Set(labels.filter(Boolean)));
  let candidate: string;
  if (unique.length === 1) candidate = unique[0];
  else if (unique.every((label) => PERIOD_LABEL.test(label))) candidate = "Period";
  else if (index === 0 && unique.some((label) => GROUP_LABEL.test(label))) candidate = "Measure lane";
  else candidate = `Dimension ${index + 1}`;

  let label = candidate;
  let suffix = 2;
  while (used.has(label)) label = `${candidate} ${suffix++}`;
  used.add(label);
  return label;
};

const rowOutputLabel = (
  row: SectionDataRow,
  descriptorValues: WorkbookCell[],
  rowById: ReadonlyMap<string, SectionDataRow>
): string => {
  const ancestors: string[] = [];
  const visited = new Set<string>();
  let current: SectionDataRow | undefined = row.parentId
    ? rowById.get(row.parentId)
    : undefined;
  while (current && !visited.has(current.id)) {
    visited.add(current.id);
    ancestors.unshift(current.label);
    current = current.parentId ? rowById.get(current.parentId) : undefined;
  }
  const descriptor = descriptorValues.map(cellText).filter(Boolean);
  return [...ancestors, ...descriptor]
    .filter((value, index, all) => Boolean(value) && value !== all[index - 1])
    .join(" · ");
};

export const normalizeSheetSection = (
  sheet: WorkbookSheet,
  requestedSelection: SectionSelection,
  providedAnalysis?: SheetSectionAnalysis
): SectionNormalization => {
  const analysis = providedAnalysis ?? analyzeSheetSections(sheet);
  const section =
    analysis.sections.find((candidate) => candidate.id === requestedSelection.sectionId) ??
    analysis.sections.find((candidate) => candidate.id === analysis.recommendedSectionId) ??
    analysis.sections[0];

  if (!section) {
    return {
      sheet: { ...sheet, sectionId: null, sectionLabel: null },
      selection: requestedSelection,
      label: "No table section detected",
      headers: sheet.headers,
      dataMatrix: sheet.dataMatrix,
      rowCount: sheet.rows.length,
      columnCount: sheet.headers.length,
    };
  }

  const matrix = sourceMatrixFor(sheet);
  const choice = section.rowChoices.find((candidate) => candidate.id === requestedSelection.rowChoiceId) ?? null;
  const selectedRows = choice
    ? section.dataRows.filter((row) => choice.rowIndices.includes(row.rowIndex))
    : section.dataRows.filter((row) => row.hasValueData);
  const allGroupIds = section.valueGroups.map((group) => group.id);
  const requestedGroups = new Set(requestedSelection.valueGroupIds);
  const matchedGroups = section.valueGroups.filter(
    (group) => requestedGroups.size === 0 || requestedGroups.has(group.id)
  );
  const selectedGroups = matchedGroups.length > 0 ? matchedGroups : section.valueGroups;
  const selectedColumnIds = new Set(selectedGroups.flatMap((group) => group.columnIds));
  let selectedValueColumns = section.valueColumns.filter((column) => selectedColumnIds.has(column.id));
  if (selectedValueColumns.length === 0) selectedValueColumns = section.valueColumns.slice(0, 1);
  const rowByIndex = new Map(selectedRows.map((row) => [row.rowIndex, row]));
  const rowById = new Map<string, SectionDataRow>(
    section.dataRows.map((row): [string, SectionDataRow] => [row.id, row])
  );
  const selectedRowIndices = selectedRows.map((row) => row.rowIndex);
  const descriptorIndices = [...section.rowLabelColumns];
  const includeParent = selectedRows.some((row) => Boolean(row.parentLabel));
  let headers: string[];
  let dataMatrix: WorkbookCell[][];

  if (requestedSelection.output === "long") {
    const valueColumns = selectedValueColumns;
    const dimensionCount = Math.max(
      0,
      ...valueColumns.map((column) => column.dimensionLabels.length)
    );
    const dimensionColumns = Array.from({ length: dimensionCount }, (_, index) =>
      dimensionHeader(
        valueColumns.map((column) => column.dimensionLabels[index] ?? ""),
        index,
        new Set<string>()
      )
    );
    headers = uniqueHeaders(["Row", ...dimensionColumns, "Measure", "Value"]);
    dataMatrix = selectedRowIndices.flatMap((rowIndex) => {
      const row = rowByIndex.get(rowIndex);
      if (!row) return [];
      const source = matrix[rowIndex] ?? [];
      const rowLabel = rowOutputLabel(
        row,
        descriptorIndices.map((columnIndex) => source[columnIndex] ?? null),
        rowById
      );
      if (valueColumns.length === 0) {
        return [[rowLabel, ...dimensionColumns.map(() => null), "Value", null]];
      }
      return valueColumns.flatMap((column) => {
        const value = source[column.columnIndex] ?? null;
        if (isBlank(value)) return [];
        const dimensions = Array.from({ length: dimensionCount }, (_, index) =>
          cellText(column.dimensionLabels[index] ?? null)
        );
        return [[rowLabel, ...dimensions, column.leafLabel, value]];
      });
    });
  } else {
    const rawHeaders = [
      ...(includeParent ? ["Row group"] : []),
      ...descriptorIndices.map((columnIndex) => {
        const path = section.valueColumns.find((column) => column.columnIndex === columnIndex)?.path;
        if (path) return path.join(" · ");
        const leafTier = section.headerTiers[section.headerTiers.length - 1]?.values[columnIndex];
        return cellText(leafTier) || `Column ${columnIndex + 1}`;
      }),
      ...selectedValueColumns.map((column) => column.label),
    ];
    headers = uniqueHeaders(rawHeaders);
    dataMatrix = selectedRowIndices.map((rowIndex) => {
      const source = matrix[rowIndex] ?? [];
      const row = rowByIndex.get(rowIndex);
      return [
        ...(includeParent ? [row?.parentLabel ?? null] : []),
        ...descriptorIndices.map((columnIndex) => source[columnIndex] ?? null),
        ...selectedValueColumns.map((column) => source[column.columnIndex] ?? null),
      ];
    });
  }

  dataMatrix = dataMatrix.map((row) =>
    Array.from({ length: headers.length }, (_, index) => row[index] ?? null)
  );
  const rows = rowsFromMatrix(dataMatrix, headers);
  const isAllGroups = allGroupIds.length === 0 || allGroupIds.every((id) => selectedGroups.some((group) => group.id === id));
  const groupLabel = isAllGroups
    ? "all measures"
    : selectedGroups.map((group) => group.label).join(" / ");
  const label = [
    section.title,
    choice?.label,
    isAllGroups ? null : groupLabel,
    requestedSelection.output === "long" ? "tidy" : "wide",
  ]
    .filter(Boolean)
    .join(" · ");
  const normalizedSheet: WorkbookSheet = {
    ...sheet,
    headers,
    rows,
    dataMatrix,
    rawRows: rows,
    filterLabel: null,
    sectionId: section.id,
    sectionLabel: label,
  };

  return {
    sheet: normalizedSheet,
    selection: {
      ...requestedSelection,
      sectionId: section.id,
      rowChoiceId: choice?.id ?? null,
      valueGroupIds: isAllGroups ? allGroupIds : selectedGroups.map((group) => group.id),
      output: requestedSelection.output,
    },
    label,
    headers,
    dataMatrix,
    rowCount: dataMatrix.length,
    columnCount: headers.length,
  };
};

export const restoreSheetFromSource = (sheet: WorkbookSheet): SectionNormalization => {
  const analysis = analyzeSheetSections(sheet);
  const selection = createDefaultSectionSelection(analysis);
  const normalized = normalizeSheetSection(sheet, selection, analysis);
  return {
    ...normalized,
    sheet: {
      ...normalized.sheet,
      sectionId: null,
      sectionLabel: null,
    },
    label: "Full active table",
  };
};